baseURL = "https://blog.kelshd.com/"
title = "Freelancer Tax"
languageCode = "en"
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
description = "Notes on design, code, and projects from Freelancer Tax"
images = ["images/og-default.jpg"]
[[menu.main]]
  name = "Store"
  url = "https://payhip.com/kelshd"
  weight = 50
