baseURL = "https://blog.kelshd.com/"
title = "UK Freelancer Survival Kit: Taxes Edition (2025)"
theme = "ananke"
themesDir = "themes"
canonifyURLs = true
enableRobotsTXT = true
languageCode = "en-gb"

[params]
  description = "Guides, notes, and insights on UK freelancer taxes"
  images = ["images/og-default.jpg"]
