baseURL = "https://blog.kelshd.com/"
title = "UK Freelancer Survival Kit: Taxes Edition (2025)"
theme = "ananke"
canonifyURLs = true
languageCode = "en-gb"
enableRobotsTXT = true
[outputs]
home = ["HTML", "RSS"]
[params]
description = "Notes on design, code, and projects from Freelancer Tax"
images = ["images/og-default.jpg"]
[[menu.main]]
  name = "Store"
  url = "https://payhip.com/b/GHlS3"
  weight = 50
