[build]
command = "hugo --gc --minify -s project_11k/site/blog -d project_11k/site/blog/public"
publish = "project_11k/site/blog/public"

[functions]
directory = "project_11k/site/blog/netlify/functions"

[[redirects]]
from = "/blog/"
to = "/posts/"
status = 301
