[build]
base = "project_11k/site/blog"
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_ENV = "staging"

[context.branch-deploy.environment]
HUGO_ENV = "staging"
