[build]
  base    = "project_11k/site/blog"
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV     = "production"
  TZ           = "Europe/London"

[context.production]
  command = "hugo --gc --minify -b https://blog.kelshd.com/"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "@netlify/plugin-github-submodules"
