baseURL = "https://blog.kelshd.com/"
title = "UK Freelancer Survival Kit: Taxes Edition (2025)"
languageCode = "en-gb"
canonifyURLs = true
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS"]

[params]
description = "UK Freelancer Survival Kit: Taxes Edition (2025) — practical guides, checklists, and resources."
images = ["images/og-default.jpg"]
theme = "ananke"

[markup.goldmark.renderer]
unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]
