baseURL = "https://blog.kelshd.com/"
title = "UK Freelancer Survival Kit: Taxes Edition (2025)"
languageCode = "en-gb"
enableRobotsTXT = true
canonifyURLs = true




[outputs]
home = ["HTML", "RSS"]

[params]
description = "Guides, notes, and insights on UK freelancer taxes"
images = ["images/og-default.jpg"]


