[build]
command = "hugo --gc --minify"
  publish = "public"
[context.production.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
[build.environment]
  GIT_SUBMODULE_STRATEGY = "recursive"

[[redirects]]
from = "/*"
to = "https://blog.kelshd.com/:splat"
status = 301
force = true
conditions = { Host = ["above-below-136d9b.netlify.app"] }

[[redirects]]
from = "/*"
to = "https://blog.kelshd.com/:splat"
status = 301
force = true
conditions = { Host = ["www.blog.kelshd.com"] }
