[build]
command = "hugo --gc --minify"
  publish = "public"
[context.production.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
[build.environment]
  GIT_SUBMODULE_STRATEGY = "recursive"

