[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "guides"
  name = "Guides"
  url = "/guides/"
  weight = 2

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 3

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 4

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 99

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 90

  [[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 91
