[params]
hero_title = "UK Freelancer Survival Kit: Taxes Edition (2025)"
hero_subtitle = "A clean, fast reference for what actually matters in UK freelancer taxes. No fluff."
cta_text = "Get the UK Freelancer Tax Kit"
payhip_url = "https://payhip.com/b/GHlS3"

[params.social]
x = "https://x.com/"
github = "https://github.com/"
linkedin = "https://www.linkedin.com/"
email = "mailto:"
