name: distribute-on-new-post
on:
  push:
    paths:
      - "project_11k/site/blog/content/posts/**.md"
  workflow_dispatch:

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install tweepy
        run: pip install --upgrade pip tweepy

      - id: find
        shell: bash
        run: |
          set -e
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"
          f="$(git diff --name-only "$BEFORE" "$AFTER" | grep '^project_11k/site/blog/content/posts/.*\.md$' | head -n1 || true)"
          if [ -z "$f" ]; then
            f="$(git show --name-only --pretty='' "$AFTER" | grep '^project_11k/site/blog/content/posts/.*\.md$' | head -n1 || true)"
          fi
          echo "file=$f" >> "$GITHUB_OUTPUT"

      - id: extract
        if: steps.find.outputs.file != ''
        shell: bash
        run: |
          f="${{ steps.find.outputs.file }}"
          title="$(grep -m1 '^title:' "$f" | sed 's/^title:[[:space:]]*["'\'']\?//; s/["'\'']$//')"
          slug="$(basename "$f" .md)"
          url="https://blog.kelshd.com/${slug}/"
          msg="${title:-New post}: ${url}"
          echo "msg=$msg" >> "$GITHUB_OUTPUT"
          echo "url=$url" >> "$GITHUB_OUTPUT"
          echo "Message: $msg"

      - name: Post to X (Twitter via OAuth 1.0a)
        if: steps.extract.outputs.msg != ''
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          MSG: ${{ steps.extract.outputs.msg }}
        run: |
          python - <<'PY'
          import os, tweepy
          api_key=os.environ["TWITTER_API_KEY"]
          api_secret=os.environ["TWITTER_API_SECRET"]
          access_token=os.environ["TWITTER_ACCESS_TOKEN"]
          access_secret=os.environ["TWITTER_ACCESS_SECRET"]
          msg=os.environ["MSG"]
          auth=tweepy.OAuth1UserHandler(api_key, api_secret, access_token, access_secret)
          api=tweepy.API(auth)
          api.update_status(status=msg)
          print("Tweeted:", msg)
          PY
