name: lighthouse-ci
on:
  schedule:
    - cron: '0 10 * * MON'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm i -g @lhci/cli@0.13.x
          lhci healthcheck || true
          lhci collect --url=https://blog.kelshd.com --numberOfRuns=3 --settings.preset=desktop --outputDir=./lhci-desktop
          lhci collect --url=https://blog.kelshd.com --numberOfRuns=3 --settings.preset=mobile --outputDir=./lhci-mobile
      - uses: actions/upload-artifact@v4
        with:
          name: lighthouse-desktop
          path: lhci-desktop
      - uses: actions/upload-artifact@v4
        with:
          name: lighthouse-mobile
          path: lhci-mobile
